---
title: "<span style = 'font-size: 100px;'>Group 14</span>"
subtitle: "<span style = 'font-size: 60px;'>Final project 14</span>"
format:
  revealjs:
    theme: moon
editor: visual
author:
- "<div style = 'text-align: center; font-size: 20px; color: gray'>Julie Brockhoff, s204519</span>"
- "<div style = 'text-align: center; font-size: 20px; color: gray'>Cecilie Kejlberg Leth, s204564</span>"
- "<div style = 'text-align: center; font-size: 20px; color: gray'>Amalie Drud Nielsen, s204560</span>"
- "<div style = 'text-align: center; font-size: 20px; color: gray'>Chrysillis Hellemann Polhaus, s153664</span>"
- "<div style = 'text-align: center; font-size: 20px; color: gray'>Lise Lotte Eriksen, s154123</span>"
---

## Introduction

::: {style="font-size: 25px; margin-top: 30px;"}
-   Human endogenous retroviruses (HERVs) have been implicated in the pathogenesis of cancers
-   Previously, a targeted knockout (KO) of HERV-K showed reduced tumorigenic attributes, such as proliferation, migration, and invasion of ovarian cancer cells
:::

\

::: {style="font-size: 40px; text-align: center;"}
**The aim of our project was to assess the effect of the HERV-K gene in two ovarian cancer cell lines by identifying differentially expressed genes (DEGs)**
:::

## Materials and methods

-   HERV-K was knocked out in two ovarian cancer cell lines: SKOV3 and OVCAR3.

    -   Next-gen mRNA sequencing was done on baseline and KO cells

-   DEG identification and plotting using R version 4.3.1

    -   with packages: tidyverse (v2.0.0) and patchwork (1.1.3)

-   KEGG enrichment using clusterProfiler (v4.10.1), biomaRt (v2.58.2) and enrichplot (v1.22.0)


## Results

```         
```

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Discussion
