---
title: "03_augment"
author: "Julie Bruun Brockhoff (s204519), Cecilie Kejlberg Leth (s204584), Amalie Drud Nielsen (s204560), Chrysillis Hellemann Polhaus (s153664), Lise Lotte Eriksen (s154123)"
format: 
  html:
    embed-resources: true
editor: visual
---

### Load packages

```{r}
library(tidyverse)
```

### Load data

```{r}
data <- read_tsv("data/02_dat_clean.tsv")
```

### Log2FC

The log2 fold change (log2FC) is calculated for each of the cell lines (OVCAR3 and SKOV3) to find assess the affect of KO.

```{r}
aug_data <- data |> 
  mutate(log2FC_OVCAR3 = log2( (OVCAR3_KO+1) / (OVCAR3_MOCK+1) ),
         log2FC_SKOV3 = log2( (SKOV3_KO+1) / (SKOV3_MOCK+1))
         ) |> 
  relocate(log2FC_OVCAR3, .after = OVCAR3_KO) |> 
  relocate(log2FC_SKOV3, .after = SKOV3_KO)
```

### Upregulated vs. downregulated

Two new columns are added (DEG_OVCAR3 and DEG_SKOV3) to the tibble that identifies whether each gene is up- or downregulated in each cell line based on the log2FC.

```{r}
aug_data <- aug_data |> 
  mutate(DEG_OVCAR3 = case_when(log2FC_OVCAR3 > 0 ~ "Upregulated",
                       log2FC_OVCAR3 < 0 ~ "Downregulated",
                       log2FC_OVCAR3 == 0 ~ "Neutral"
                       ),
         DEG_SKOV3 = case_when(log2FC_SKOV3 > 0 ~ "Upregulated",
                       log2FC_SKOV3 < 0 ~ "Downregulated",
                       log2FC_SKOV3 == 0 ~ "Neutral"
                       )
  ) |> 
  relocate(DEG_OVCAR3, .after = log2FC_OVCAR3) |> 
  relocate(DEG_SKOV3, .after = log2FC_SKOV3)
```

### Save data for later use

```{r}
#Then save it to the data folder for later use 
write_tsv(aug_data, "data/03_dat_aug.tsv")
```
