---
title: "07_analysis_3"
author: "Julie Bruun Brockhoff (s204519), Cecilie Kejlberg Leth (s204584), Amalie Drud Nielsen (s204560), Chrysillis Hellemann Polhaus (s153664), Lise Lotte Eriksen (s154123)"
format: 
  html:
    embed-resources: true
editor: visual
  markdown: 
    wrap: 72
---

### Load packages

```{r}
library(tidyverse)
library(broom)
```

### Load data

```{r}
data <- read_tsv("../data/03_dat_aug.tsv")
```

```{r}
mock_or_ko <- data |> 
  select(gene, 
         contains("MOCK"), 
         contains("_KO")) |> 
  pivot_longer(cols = c(OVCAR3_MOCK, 
                        OVCAR3_KO, 
                        SKOV3_MOCK, 
                        SKOV3_KO), 
               names_to = c(".value", 
                            "MOCK_or_KO"), 
               names_pattern = "(.*)_(.*)" )
```

### Alm scatter plot over de to

To show the nicest version of the plot, some rows are removed

```{r}
mock_or_ko |> 
  ggplot(mapping = aes(x = OVCAR3, y = SKOV3, color = MOCK_or_KO)) +
  geom_point() + 
  geom_smooth(method = lm,
              se = FALSE) +
  labs(title = "Gene expression in the two cell lines for MOCK and KO",
       color = "MOCK or KO") +
  theme_minimal() +
  scale_x_continuous(limits = c(0,730000)) +
  scale_y_continuous(limits = c(0,730000))
```

### Correlation for the regression

Though some points are removed in the plot above, all values are a part of the models beneath. Therefore the models beneath are not equal to the regressions above.

```{r}
model_KO <- mock_or_ko |> 
  filter(MOCK_or_KO == "KO") |> 
  lm(formula = SKOV3 ~ OVCAR3)

model_MOCK <- mock_or_ko |> 
  filter(MOCK_or_KO == "MOCK") |> 
  lm(formula = SKOV3 ~ OVCAR3)

model_KO
model_MOCK

rho_KO <- mock_or_ko |> 
  filter(MOCK_or_KO == "KO") |> 
  select(OVCAR3,
         SKOV3) |> 
  cor(method = "spearman")

rho_MOCK <- mock_or_ko |> 
  filter(MOCK_or_KO == "MOCK") |> 
  select(OVCAR3,
         SKOV3) |> 
  cor(method = "spearman")

rho_KO
rho_MOCK
```

```{r}
KO_OVCAR3 <- mock_or_ko |> 
  filter(MOCK_or_KO == "KO") |> 
  select(OVCAR3)
MOCK_OVCAR3 <- mock_or_ko |> 
  filter(MOCK_or_KO == "MOCK") |> 
  select(OVCAR3)

broom::tidy(t.test(KO_OVCAR3, MOCK_OVCAR3), paired = TRUE)|> 
  pull(p.value)


KO_SKOV3 <- mock_or_ko |> 
  filter(MOCK_or_KO == "KO") |> 
  select(SKOV3)
MOCK_SKOV3 <- mock_or_ko |> 
  filter(MOCK_or_KO == "MOCK") |> 
  select(SKOV3)

broom::tidy(t.test(KO_SKOV3, MOCK_SKOV3), paired = TRUE)|> 
  pull(p.value)
```
