---
title: "07_analysis_3"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

### Load Packages
```{r}
library(tidyverse)
```

### Load data
```{r}
data <- read_tsv("data/03_dat_aug.tsv")
```

### Heatmap
```{r}
#jeg har samplet 70 random gener - jeg ved ikke hvordan det giver mening at filtrere generne
data |>
  sample_n(70) |> 
  pivot_longer(
    cols = c(log2FC_OVCAR3, log2FC_SKOV3), 
    names_to = "cell_line", 
    values_to = "log2_expression") |> 
  ggplot(mapping = aes(x = gene,
                       y = cell_line,
                       fill = log2_expression)) +
  geom_tile() +
  scale_fill_gradient2(midpoint = 0,
                       low = "blue",
                       mid = "white",
                       high = "red") +
  labs(x = "Gene",
       y = "Cell line",
       title = "Log2 gene expression differences from baseline to HERV-K knockouts in SKOV3 and OVCAR3 cells",
       fill = "Log2 expression") +
  theme_classic() +
  theme(axis.title.x = element_text(size = 16),
        axis.text.x = element_text(size = 12,
                                   angle = 45, 
                                   hjust = 1),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 12)) +
  scale_y_discrete(labels = c("log2FC_SKOV3" = "SKOV3", "log2FC_OVCAR3" = "OVCAR3"))

```

