---
title: "Analysis 1"
author: "Julie Bruun Brockhoff (s204519), Cecilie Kejlberg Leth (s204584), Amalie Drud Nielsen (s204560), Chrysillis Hellemann Polhaus (s153664), Lise Lotte Eriksen (s154123)"
format: 
  html:
    embed-resources: true
editor: visual
---

## Load packages

```{r}
library(tidyverse)
library(broom)
```

### Load data

```{r}
data <- read_tsv("../data/03_dat_aug.tsv")
```

### Statistics

#### OVCAR3

```{r}
# Add p-values using t-tests
data_test <- data |> 
  rowwise() |> # Perform row-wise operations
  mutate(
    p_value_OVCAR3 = broom::tidy(t.test(OVCAR3_MOCK, OVCAR3_KO, paired = TRUE)) |> 
                pull(p.value)
  ) |>
  ungroup() # Return to a standard tibble


```

#### SKOV3

### Volcano plots

#### OVCAR3

Add variable `q.value` and indicator variable `significant` to identify significant and non-significant genes:

```{r}
OVCAR3_estimates <- OVCAR3_estimates |> 
  mutate(q.value = p.adjust(p.value)) |> 
  mutate(significant = case_when(p.value > 0.05 ~ "no",
                                 p.value < 0.05 ~ "yes"))
```

Create volcano plot:

```{r}
OVCAR3_estimates |> 
  mutate(lbl = case_when(significant == "yes" ~ gene,
                           significant == "no" ~ "")) |> 
  ggplot(mapping = aes(x = estimate,
                       y = -log10(p.value),
                       colour = significant,
                       label = lbl)) +
  geom_point(size = 1,
             alpha = 0.5) +
  geom_text_repel(size = 4,
                  max.overlaps = 20) +
  geom_hline(yintercept = 0) +
  theme_minimal(base_size = 9) +
  theme(plot.title = element_text(hjust = 1),
        plot.subtitle = element_text(hjust = 1),
        legend.position = "none") +
  labs(
    x = "Estimates",
    y = "-log10(p)",
    title = "Genes Associated with HERV‑K env gene knockout in ovarian cancer OVCAR3 cell line",
    subtitle = "Genes highlighted in turquoise are significant",
    caption = "Data from DOI: 10.1007/s13258-024-01544-4")
```

#### SKOV3
